app/models/faba_model.py
from app.extensions import db

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    content = db.Column(db.Text)

    def __repr__(self):
        return f'<Post "{self.title}">'

app/__init__.py
from flask import Flask, redirect, url_for, session

from config import Config
from app.extensions import db

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Initialize Flask extensions here
    db.init_app(app)
    
    # Register blueprints here
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.addons.faba import bp as faba_bp
    app.register_blueprint(faba_bp, url_prefix="/faba")

    @app.route("/login")
    def login():
        session["loggedin"] = True
        session["username"] = "admin"
        return redirect(url_for("main.index"))
    
    @app.route("/logout")
    def logout():
        session.pop("loggedin", None)
        session.pop("username", None)

        return redirect(url_for("main.index"))

    return app

app/addons/faba/__init__.py
from flask import Blueprint

bp = Blueprint("faba", __name__)

from app.addons.faba import routes

app/addons/faba/routes.py
from flask import render_template, redirect, url_for, request, session
from app.addons.faba import bp
from app.models.faba_model import Post
from app.extensions import db

@bp.route("/")
def index():
    if 'loggedin' in session:
        results = Post.query.all()
        return render_template("faba/index.html", content=results)

    return redirect(url_for('main.index'))

@bp.route("/transporter")
def transporter():
    if 'loggedin' in session:
        return render_template("faba/transporter.html")
    
    return redirect(url_for('main.index'))

@bp.route("/post", methods=["GET", "POST"])
def post():
    if 'loggedin' in session:
        if request.method == "POST":
            title = request.form["title"]
            content = request.form["content"]
            
            # commit
            content_post = Post(title=title, content=content)
            db.session.add(content_post)
            db.session.commit()

        return redirect(url_for('faba.index'))
    
    return redirect(url_for('main.index')) 

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import session
from app.main import bp

@bp.route('/')
def index():
    if 'loggedin' in session:
        return 'Your loggedin as ' + session["username"] + ' <a href="/logout">Logout</a>'
    return 'Portal Apps ' + ' <a href="/login">Login</a>'

app/templates/faba/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock title %} - Faba</title>
</head>
<body>
    <h1>Welcome</h1>
    <p><a href="{{url_for('main.index')}}">Back to Portal Apps</a></p>
    <ul>
        <li><a href="{{url_for('faba.index')}}">Home</a></li>
        <li><a href="{{url_for('faba.transporter')}}">Transporter</a></li>
    </ul>
    <div style="background-color: aqua;">
    {% block content %}
    {% endblock content %}
    </div>
    <h1>Footer</h1>
</body>
</html>

app/templates/faba/index.html
{% extends "faba/base.html" %}
{% block title %}Home{% endblock title %}
{% block content %}
{% for post in content %}
<h1>{{post.title}}</h1>
<p>{{post.content}}</p>
{% endfor %}
{% endblock content %}

app/templates/faba/transporter.html
{% extends "faba/base.html" %}
{% block title %}Transporter{% endblock title %}
{% block content %}
<h1>This is Transporter Content</h1>
<form action="{{url_for('faba.post')}}" method="post">
    <p><input type="text" name="title" placeholder="Title"></p>
    <p><textarea name="content"cols="30" rows="10" placeholder="Content"></textarea></p>
    <p><input type="submit" value="Post"></form></p>
</form>
{% endblock content %}